[package]
name = "mini_tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tun-tap = "0.1.2"
etherparse= "0.8"
bitflags = "2.8.0"
nix = "0.22.0"

[lib]
name = "mini_tcp"

[[bin]]
name = "mini_tcp"